---


- name: deploy backend
  become_user: true
  unarchive:
    src: /etc/artifact.tar.gz
    dest: ~/

- name: run backend
  become_user: true
  shell: |
    cd ~/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 ls
    